[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
[tool.poetry.dependencies]
requests = "^2.13.0"
python = "^3.10"
websockets = "^10.1"
bitstring = "^3.1.9"
